version: "3.9"

services:
    ultra-janitorial-nginx:
        image: defalt115/ultra-janitorial-txy:v0.2
        restart: unless-stopped
        ports: 
            - 80:80
        depends_on: 
            - txy-server
    txy-server:
        image: defalt115/txy_server:v1
        restart: unless-stopped
        ports:
            - 5000:5000
        environment: 
            - HOST=0.0.0.0
            - PORT=5000
        volumes: 
            - ./txy:/content
        